-- CRM SALES DATA OVERVIEW
/* This project utilizes four interconnnected tables to analyze sales performance, product adoption
and account development trends.
* The account table contains key information about customer companies. Field name account was the unique
indentifier for the account (PRIMARY KEY).
* Products table contains details of the product offered by the company where product field was the 
specific product name (PRIMARY KEY).
* Sales team table maps sales agent to their managers and operational regions where saleagent field
 represents the ID of the sale agent responsible for the deals(PRIMARY KEY)
*  Sales pipeline table captures all sales activities, opportunities and closed deals where opportunity id
 was the unique indentifier for each sales opportunity (PRIMARY KEY), sales agent (FOREIGN KEY),
 products (FOREIGN KEY) and account (FOREIGN KEY) */

/* Purpose of this project 
* Analyze sales funnel performance by managers, sales agent and sector.
* Indentify high value accounts, products and sector contributing to the most revenue
* Track sales pipeline over time(lost opportunity, monthly rates)
* Pinpoint underperforming areas (accounts, managers, agents)
*/


select * from accounts;

select * from products;

select * from sales_pipeline;

select * from sales_team;


-- QUESTION: WHICH ACCOUNTS HAVE ATLEAST WON ONE DEAL, AND WHAT IS THE TOTAL REVENUE FROM THEM
-- GOAL: INDENTIFY VALUABLE CUSTOMERS CONTRIBUTING TO THE COMPANY REVENUE

SELECT ACCOUNT_NAME, SUM(CLOSE_VALUE) AS TOTAL_REVENUE
FROM sales_pipeline
WHERE deal_stage = "Won"
GROUP BY ACCOUNT_NAME
ORDER BY TOTAL_REVENUE DESC;

/* ANALYSIS: For accounts for Kan-code, konex;we need to focus on retention efforts and loyalty 
programs for these accounts since these accounts generating the top revenue */

-- Q: HOW MANY TOTAL WON DEALS AND LOST DEALS ARE RECORDED PER SALES AGENT
-- GOAL: EVALUATE BASIC PERFORMANCE OF EACH SALES AGENT

SELECT SALES_AGENT, COUNT(*) AS TOTAL_DEALS,
SUM(CASE WHEN DEAL_STAGE = 'WON' THEN 1 ELSE 0 END) AS WON_DEALS,
SUM(CASE WHEN DEAL_STAGE = 'LOST' THEN 1 ELSE 0 END) AS LOST_DEALS
FROM SALES_PIPELINE
GROUP BY SALES_AGENT
ORDER BY WON_DEALS DESC;

/* This query indentifies agents with high volume of deals,lost deals and the won deals. Anna
Snelling has the high volume of deals with the highest winning rate */

-- Q: WHO ARE THE TOP RANKED SALES AGENTS BASED ON CLOSED DEALS WITHIN EACH OFFICE LOCATION
-- GOAL: RECOGNIZE TOP REGIONAL PERFORMERS AND STIMULATE COMPETITION ACROSS OFFICES

SELECT SP.SALES_AGENT, A.OFFICE_LOC, SUM(SP.CLOSE_VALUE) AS TOTAL_CLOSE_DEALS,
DENSE_RANK() OVER(PARTITION BY A.OFFICE_LOC ORDER BY SUM(SP.CLOSE_VALUE) DESC) AS AGENT_RANK
FROM SALES_PIPELINE SP
INNER JOIN ACCOUNTS A ON SP.ACCOUNT_NAME = A.ACCOUNT_NAME
GROUP BY SP.SALES_AGENT, A.OFFICE_LOC;

/* This query indentifies high performing sales agent based on their regional office, for example
Darcel is the top performer for USA/Belgium region with most closed deals. Regions constanstly dominated
by one or two agents might suggest an over reliance; succession planning is needed */


-- Q: WHAT ARE THE TOP SELLING PRODUCTS BY SERIES BASED ON TOTAL SALES PRICE
-- GOAL: INDENTIFY LEADING PRODUCTS TO OPTIMIZE STOCK AND PROMOTION

WITH TOP_PRODUCT AS
( SELECT PRODUCT, SERIES, SUM(SALES_PRICE) AS TOTAL_PRICE,
DENSE_RANK() OVER(PARTITION BY SERIES ORDER BY SUM(SALES_PRICE) DESC) AS TOP_RANK
FROM PRODUCTS
GROUP BY PRODUCT, SERIES)
select * FROM TOP_PRODUCT
WHERE TOP_RANK = 1;

/* The top product here is GTK 500 and it should be prioritized for marketing, cross selling 
and inventory planning while underforming series may need promotinal discounts */

-- Q: HIW LONG DOES IT TAKE ON AVG TO CLOSE A DEAL IN EACH SECTOR
-- GOAL: BENCHMARK SECTOR SPECIFIC SALE CYCLE TO OPTIMIZE RESOURCE ALLOCATION,
-- FORECAST REVENUE AND SET REALISTIC SALES TARGETS

SELECT A.SECTOR, ROUND(AVG(DATEDIFF(SP.CLOSE_DATE, SP.ENGAGE_DATE))) AS AVERAGE_NO_DAYS
FROM SALES_PIPELINE SP
INNER JOIN ACCOUNTS A ON SP.ACCOUNT_NAME = A.ACCOUNT_NAME
WHERE SP.DEAL_STAGE = "WON"
GROUP BY A.SECTOR
ORDER BY AVERAGE_NO_DAYS DESC;

/* SECTORS WITH LONGER CLOSE TIME LIKE EMPLOYMENT AND TELECOMMUNICATIONS MAY REQUIRE LONGER 
NUTURING AND FOLLOW UP CAMPAIGNS. KNOWING CLOSED TIMES CAN IMPROVE EXPECTED REVENUE TIMELINES */

-- QUESTION: WHAT IS THE MOST RECENT DEAL FOR EACH ACCOUNT
-- GOAL:TO MAINTAIN CLIENT ENGAGEMENT AND INDENTIFY NEW RE-ENGAGEMENT OPPORTUNITIES 

WITH MOST_RECENT_DEAL AS
(SELECT ACCOUNT_NAME, CLOSE_VALUE, DEAL_STAGE, CLOSE_DATE,
DENSE_RANK() OVER(partition by ACCOUNT_NAME ORDER BY CLOSE_DATE DESC) AS RECENT_DEAL
FROM SALES_PIPELINE)
SELECT ACCOUNT_NAME, CLOSE_VALUE, DEAL_STAGE, CLOSE_DATE
FROM MOST_RECENT_DEAL
WHERE RECENT_DEAL = 1;

/* ORDERS WITHOUT RECENT DEALS MAYBE AT CHURN RISK - TRIGGER A REACTIVATION CAMPAIGN AND RECENT WINS
LIKE ACME CORPORATION SIGNAL LEADS FOR PRODUCT PITCHES. */

-- Q: HOW HAS EACH SALES AGENT REVENUE CHANGED OVER TIME
-- GOAL: TRACK REVENUE GROWTH/DECLINE PER SALES AGENT TO SPOT THE TRENDS EARLY

WITH SALES_REVENUE AS 
(SELECT SALES_AGENT, CLOSE_DATE, SUM(CLOSE_VALUE) AS CURRENT_REVENUE,
LAG(SUM(CLOSE_VALUE)) OVER (partition by SALES_AGENT ORDER BY (CLOSE_DATE)) AS PREVIOUS_REVENUE
FROM SALES_PIPELINE
GROUP BY SALES_AGENT,CLOSE_DATE)
SELECT SALES_AGENT, CLOSE_DATE, CURRENT_REVENUE - coalesce(PREVIOUS_REVENUE,0) AS REVENUE_DIFFERENCE
FROM SALES_REVENUE;

/* AGENTS SHOWING CONTINOUS GROWTH CAN BE STRONG CANDIDATES FOR LEADERSHIP ROLES WHILE DECLINING
CANDIDATES MIGHT INDICATE LOSS OF KEY ACCOUNT */

-- Q: WHAT IS EACH ACCOUNTS WIN RATE AND WHICH ACCOUNTS HAVE A WIN RATE BELOW 60%
-- GOAL: INDENTIFY UNDERPERFOMING ACCOUNTS BASED ON DERIVED WIN RATE METRICS

WITH ACCOUNT_DEAL AS 
(SELECT ACCOUNT_NAME, COUNT(DEAL_STAGE) AS TOTAL_DEALS,
SUM(CASE WHEN DEAL_STAGE = 'WON' THEN 1 ELSE 0 END) AS WON_DEALS
FROM SALES_PIPELINE
GROUP BY ACCOUNT_NAME)
SELECT ACCOUNT_NAME, ROUND(WON_DEALS/TOTAL_DEALS,2) AS WIN_RATE
FROM ACCOUNT_DEAL
WHERE WON_DEALS/TOTAL_DEALS < 0.60;

/* THIS INSIGHT SURFACES ACCOUNTS LIKE BLACKZIM, BLUTH COMPANY ARE ENGAGING IN MULTIPLE DEALS BUT
FAILING TO CONVERT MOST OF THEM. THESE ACCOUNTS NEED A DEEPER INVESTIGATION */

-- Q: WHAT IS MONTHLY TREND OF TOTAL DEALS,WON DEALS AND LOSS DEALS 
-- GOAL: UNDERSTAND THE SALES PERFORMANCE OVER TIME TO INDENITFY SEASONALITY OR MOMENTUM SHIFTS

SELECT DATE_FORMAT(CLOSE_DATE, '%Y-%m') AS MONTHS
FROM SALES_PIPELINE;

SELECT DATE_FORMAT(CLOSE_DATE, '%Y-%m') AS MONTHS, COUNT(DEAL_STAGE) AS TOTAL_DEALS,
SUM(CASE WHEN DEAL_STAGE = 'WON' THEN 1 ELSE 0 END) AS WON_DEALS,
SUM(CASE WHEN DEAL_STAGE = 'LOST' THEN 1 ELSE 0 END) AS LOST_DEALS
FROM SALES_PIPELINE
GROUP BY DATE_FORMAT(CLOSE_DATE,'%Y-%m') 
ORDER BY MONTHS;

/* MONTHLY TRACKING OF DEAL OUTCOMES ENABLES TREND DETECTION AND FORECASTING. A SPIKE IN LOSSES OR 
DIP IN WINS IN CERTAIN MONTHS CAN HIGHLIGHT POOR CAMPAIGN TIMINGS OR PRODUCT MARKET MISFIT */


-- Q: WHICH ACCOUNT HAVE BOTH LOST DEALS AND HAVE SHOWN AN INCREASE IN DEAL VALUE OVER TIME
-- AND WHICH SECTOR DO THEY BELONG TO
-- GOAL: INDENTIFY DETECT UNDERPERFORMING ACCOUNTS DESPITE LOSSES ARE INCREASING IN PURCHASE VALUE,
-- SIGNALING POTENTIAL FOR RECOVERY

WITH LOST_DEALS AS 
(SELECT SP.ACCOUNT_NAME, SP.DEAL_STAGE AS DEAL_STATUS, A.SECTOR
FROM SALES_PIPELINE SP
INNER JOIN ACCOUNTS A ON SP.ACCOUNT_NAME = A.ACCOUNT_NAME
WHERE SP.DEAL_STAGE = 'LOST'),

WON_DEALS AS
(SELECT ACCOUNT_NAME,CLOSE_DATE,CLOSE_VALUE AS CURRENT_VALUE, 
coalesce(LAG(CLOSE_VALUE) OVER (PARTITION BY ACCOUNT_NAME ORDER BY CLOSE_DATE),0) AS PREVIOUS_VALUE,
COALESCE(CLOSE_VALUE - LAG(CLOSE_VALUE) OVER (PARTITION BY ACCOUNT_NAME ORDER BY CLOSE_DATE),0) AS CHANGE_IN_VALUE
FROM SALES_PIPELINE
 WHERE DEAL_STAGE = 'WON'
ORDER BY ACCOUNT_NAME, CLOSE_DATE)
SELECT WD.ACCOUNT_NAME, LD.SECTOR, WD.CLOSE_DATE, WD.CURRENT_VALUE, LD.DEAL_STATUS, 
WD.CURRENT_VALUE, WD.PREVIOUS_VALUE, WD.CHANGE_IN_VALUE
FROM WON_DEALS WD
INNER JOIN LOST_DEALS LD ON WD.ACCOUNT_NAME = LD.ACCOUNT_NAME
ORDER BY WD.CHANGE_IN_VALUE DESC;

/* THESE ACCOUNT REFLECT MIXED PERFORMANCE AND ARE NOT FULLY DISENGAGED INSTEAD THEY SHOW PURCHASE
VALUE GROWTH */


/* Q: HOW DO INDIVIDUAL SALES MANAGERS PERFORM IN TERMS OF OVERALL DEAL OUTCOMES, 
 AND WHICH SALES AGENTS UNDER THEM ARE THE MOST EFFECTIVE BASED ON WIN RATE AND TOTAL DEAL VALUE.
 GOAL: TO PROVIDE LEADERSHIP WITH A COMPREHENSIVE PERFORMANCE SUMMARY OF EACH SALES MANAGER FOCUSING
 ON AVG DEAL VALUE FROM WON DEALS, WIN RATE PER SALES AGENT,
 INDENTIFYING THE TOP PERFORMING AGENT PER MANAGER BASED TOTAL DEAL VALUE FROM CLOSED WON DEALS. */

WITH AGENT_STATS AS
(SELECT ST.MANAGER,SP.SALES_AGENT, COUNT(SP.DEAL_STAGE) AS TOTAL_DEALS, 
SUM(SP.CLOSE_VALUE) AS TOTAL_VALUE,
SUM(CASE WHEN DEAL_STAGE = 'WON' THEN 1 ELSE 0 END) AS TOTAL_WON_DEAL,
AVG(CASE WHEN DEAL_STAGE = 'WON' THEN CLOSE_VALUE ELSE NULL END) AS AVG_WON_VALUE
FROM SALES_PIPELINE SP
INNER JOIN SALES_TEAM ST ON SP.SALES_AGENT = ST.SALES_AGENT
GROUP BY ST.MANAGER, SP.SALES_AGENT),
AGENT_RANK AS
(SELECT *,
RANK() OVER(PARTITION BY MANAGER ORDER BY TOTAL_VALUE) AS AGENT_RANK, TOTAL_WON_DEAL/TOTAL_DEALS
AS WIN_RATE
FROM AGENT_STATS)
SELECT MANAGER, SALES_AGENT, TOTAL_VALUE, AVG_WON_VALUE, TOTAL_WON_DEAL, 
WIN_RATE, AGENT_RANK 
FROM AGENT_RANK
WHERE AGENT_RANK = 1 OR WIN_RATE > .7
ORDER BY TOTAL_VALUE, TOTAL_WON_DEAL, WIN_RATE;

/* ANALYSIS: BY AGGREGATING METRICS LIKE AVG WON VALUE, WIN RATE AND TOTAL WON DEAL, THIS REPORT
IDENTIFIES MANAGERS LIKE CARA,MELVIN CONSISTENTLY DELIVERED HIGH VALUE DEALS AND SALES AGENT LIKE
ROSALINA OUTPERFORMED OTHER WITHIN THE SAME TEAM,
THE RANK() LOGIC PINPOINTS TOP AGENTS PER MANAGER SURFACING HIGH POTENTIAL TALENT,
FILTERING FOR AGENTS OR FILTERING WIN RATE > 70% CAPTURES TOP STRONG PERFORMERS WHO MIGHT NOT BE 
TOP IN RAW VALUE BUT SHOW HIGH EFFICIENCY IN CONVERSIONS */

/* Q: HOW DO DIFFERENT PRODUCT SERIES PERFORM ACROSS SECTORS IN TERMS OF REVENUE, 
ACCOUNT ADOPTION AND STRATEGIC ACCOUNT WINS? 
-- FOR EACH PRODUCT SERIES GENERATE A REPORT THAT SHOWS 
-- TOTAL REVENUE GENERATED PER SECTOR FROM WON DEALS ONLY 
-- NO OF UNIQUE ACCOUNTS THAT PURCHASED FROM EACH SERIES PER SECTOR
-- THE TOP ACCOUNT(TOTAL CLOSE VALUE) IN EACH SECTOR FOR THAT PRODUCT SERIES

GOAL: TO GUIDE PRODUCT STRATERGY AND CROSS FUNCTIONAL ALIGNMENT BETWEEN SALES AND PRODUCT TEAMS
BY: 
* MEASURING TOTAL REVENUE PER PRODUCT SERIES PER SECTOR 
* BY COUNTING HOW MANY UNIQUE ACCOUNTS BOUGHT EACH PRODUCT SERIES IN EACH SECTOR, WE CAN SEE HOW
WIDELY ADOPTED A PRODUCT IS ACROSS INDUSTRIES
* HIGHLY TOP REVENUE GENERATING ACCOUNTS PER SECTOR-PRODUCT COMBINATION 
THIS GIVES CLARITY ON WHERE EACH PRODUCT PERFORMS BEST AND CROSS SELLING OR UPSELLING MAYBE UNDER LEVEREGED */ 

-- AGGREGATES REVENUE PER ACCOUNT PER SERIES AND SECTOR
WITH SECTOR_REVENUE AS 
(SELECT P.SERIES, SP.ACCOUNT_NAME,SUM(SP.CLOSE_VALUE) AS TOTAL_REVENUE,A.SECTOR
FROM SALES_PIPELINE SP
INNER JOIN PRODUCTS P ON SP.PRODUCT = P.PRODUCT
INNER JOIN ACCOUNTS A ON SP.ACCOUNT_NAME = A.ACCOUNT_NAME
WHERE DEAL_STAGE = 'WON'
GROUP BY P.SERIES, SP.ACCOUNT_NAME, A.SECTOR
),

SECTOR_SUMMARY AS 
(SELECT SERIES,SECTOR,SUM(TOTAL_REVENUE) AS TOTAL_SECTOR_REVENUE,COUNT(DISTINCT ACCOUNT_NAME) AS UNIQUE_ACCOUNTS
FROM SECTOR_REVENUE GROUP BY SERIES, SECTOR),

TOP_ACCOUNT_PER_SECTOR_SERIES AS 
(SELECT SERIES,SECTOR,ACCOUNT_NAME,TOTAL_REVENUE,
RANK() OVER (PARTITION BY SERIES, SECTOR ORDER BY TOTAL_REVENUE DESC) AS SECTOR_RANK
FROM SECTOR_REVENUE
)

SELECT SS.SERIES,SS.SECTOR,SS.TOTAL_SECTOR_REVENUE,SS.UNIQUE_ACCOUNTS,
TP.ACCOUNT_NAME AS TOP_ACCOUNT,
TP.TOTAL_REVENUE AS TOP_ACCOUNT_VALUE
FROM SECTOR_SUMMARY SS
INNER JOIN TOP_ACCOUNT_PER_SECTOR_SERIES TP 
ON SS.SERIES = TP.SERIES 
AND SS.SECTOR = TP.SECTOR
WHERE TP.SECTOR_RANK = 1
ORDER BY SERIES, TOTAL_SECTOR_REVENUE DESC;

/*ANALYSIS: BY CALCULATING TOTAL REVENUE ONLY FROM WON DEALS PER PRODUCT SERIES ACROSS SECTORS 
SHOWS WHERE EACH PRODUCT IS GENERATING REAL SALES IMPACT AND WHICH SECTORS ARE REVENUE RICH FOR 
SPECIFIC SERIES. FOR EXAMPLE RETAIL IS THE TOP REVENUE GENERATING SECTOR FOR GTX SERIES WHILE 
ENTERTAINMENT IS THE TOP REVENUE GENERATING SECTOR FOR GTK.
THIS BREAKDOWN BY SERIES AND SECTOR GIVES A COMPLETE VIEW REVENUE CONCENTRATION AND 
ADOPTION DIVERSITY.
IT INDENTIFIES TOP ACCOUNTS LIKE Y-CORP AND CHEERS PER SECTOR & SERIES, IT UNCOVERS WHICH CLIENTS
ARE THE MOST VALUABLE HELPING IN PRIORITIZING RENTENTION, CUSTOM OFFERS OR CASE STUDIES.
IF PRODUCT SERIES LIKE GTK IS GENERATING 65% OF IT'S REVENUE FROM ENTERTAINMENT SECTOR, IT IS A CLEAR
TO DOUBLE DOWN ON SECTOR SPECIFIC CAMPAIGNS. */































